In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# Read and Observe the Dataset.

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
reader = pd.read_csv("/content/drive/MyDrive/Datasets/student.csv")
df = pd.DataFrame(reader)


# Print top(5) and bottom(5) of the dataset {Hint: pd.head and pd.tail}

In [9]:
df.head(5)

Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [10]:
df.tail(5)

Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

# Print the Information of Datasets. {Hint: pd.info}.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB


# Gather the Descriptive info about the Dataset. {Hint: pd.describe}

In [12]:
df.describe()

Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000

# Split your data into Feature (X) and Label (Y).

In [13]:
import pandas as pd
# Splitting the data into Features (X) and Labels (Y)
X = df.iloc[:, :-1]  # Assuming all columns except the last are features
Y = df.iloc[:, -1]   # Assuming the last column is the label
X.head()

Math  Reading
0    48       68
1    62       81
2    79       80
3    76       83
4    59       64

In [14]:
Y.head()

0    63
1    72
2    78
3    79
4    62
Name: Writing, dtype: int64

In [15]:
X_matrix = X.T.to_numpy()
Y_matrix = Y.to_numpy().reshape(-1, 1)

W = np.random.rand(X_matrix.shape[0], 1)

Y_hat = np.dot(W.T, X_matrix)

print("Shape of Feature Matrix (X):", X_matrix.shape)
print("Shape of Weight Vector (W):", W.shape)
print("Shape of Target Vector (Y):", Y_matrix.shape)
print("Shape of Predicted Y (Y_hat):", Y_hat.shape)

print("\nSample Feature Matrix (X):")
print(X_matrix[:, :5])

print("\nSample Weight Vector (W):")
print(W)

print("\nSample Target Vector (Y):")
print(Y_matrix[:5])

print("\nSample Predicted Y (Y_hat):")
print(Y_hat[:, :5])

Shape of Feature Matrix (X): (2, 1000)
Shape of Weight Vector (W): (2, 1)
Shape of Target Vector (Y): (1000, 1)
Shape of Predicted Y (Y_hat): (1, 1000)

Sample Feature Matrix (X):
[[48 62 79 76 59]
 [68 81 80 83 64]]

Sample Weight Vector (W):
[[0.70010948]
 [0.44206109]]

Sample Target Vector (Y):
[[63]
 [72]
 [78]
 [79]
 [62]]

Sample Predicted Y (Y_hat):
[[63.66540897 79.21373582 90.67353586 89.89939069 69.59836888]]


In [16]:
# Step 1: Split the dataset into training and testing sets (80-20 split)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42) # Transpose X back to (1000, 2)

# Check the dimensions of the split data
print("Training Data (X_train) Shape:", X_train.shape)
print("Testing Data (X_test) Shape:", X_test.shape)
print("Training Labels (Y_train) Shape:", Y_train.shape)
print("Testing Labels (Y_test) Shape:", Y_test.shape)

# Optionally, if you want to confirm the split visually:
# Print the first few entries of X_train and Y_train
print("\nFirst few entries of X_train:\n", X_train[:5])
print("\nFirst few entries of Y_train:\n", Y_train[:5])

Training Data (X_train) Shape: (800, 2)
Testing Data (X_test) Shape: (200, 2)
Training Labels (Y_train) Shape: (800,)
Testing Labels (Y_test) Shape: (200,)

First few entries of X_train:
      Math  Reading
29     64       82
535    62       70
695    36       21
557    81       70
836    82       86

First few entries of Y_train:
 29     78
535    67
695    25
557    71
836    87
Name: Writing, dtype: int64


In [17]:
def cost_function(X, Y, W):
    """
    Parameters:
    X : numpy.ndarray
        Feature matrix (d x n), where d is the number of features and n is the number of samples.
    Y : numpy.ndarray
        Target vector (n, ), where n is the number of samples.
    W : numpy.ndarray
        Weight vector (d, ), where d is the number of features.

    Output:
    cost : float
        The accumulated mean squared error (MSE).
    """
    # Step 1: Calculate the predicted values (Y_hat) using the linear model
    Y_pred = np.dot(X, W)  # X * W gives the predicted values

    # Step 2: Calculate the squared errors between the predicted and actual values
    errors = Y - Y_pred

    # Step 3: Compute the Mean Squared Error (MSE)
    cost = np.mean(errors ** 2)  # MSE = average of squared errors

    return cost

In [18]:
# Define the cost function
def cost_function(X, Y, W):
    """
    Parameters:
    X : numpy.ndarray
        Feature matrix (d x n), where d is the number of features and n is the number of samples.
    Y : numpy.ndarray
        Target vector (n, ), where n is the number of samples.
    W : numpy.ndarray
        Weight vector (d, ), where d is the number of features.

    Output:
    cost : float
        The accumulated mean squared error (MSE).
    """
    # Step 1: Calculate the predicted values (Y_hat) using the linear model
    Y_pred = np.dot(X, W)  # X * W gives the predicted values

    # Step 2: Calculate the squared errors between the predicted and actual values
    errors = Y - Y_pred

    # Step 3: Compute the Mean Squared Error (MSE)
    cost = np.mean(errors ** 2)  # MSE = average of squared errors

    return cost

# Test case
X_test = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
Y_test = np.array([3, 7, 11])
W_test = np.array([1, 1])

# Calculate the cost
cost = cost_function(X_test, Y_test, W_test)

# Check if the cost is as expected (0)
if cost == 0:
    print("Proceed Further")
else:
    print("Something went wrong: Reimplement the cost function")

print("Cost function output:", cost)

Proceed Further
Cost function output: 0.0


In [19]:

# Define the cost function
def cost_function(X, Y, W):
    """
    Parameters:
    X : numpy.ndarray
        Feature matrix (m x n), where m is the number of samples and n is the number of features.
    Y : numpy.ndarray
        Target vector (m, ), where m is the number of samples.
    W : numpy.ndarray
        Weight vector (n, ), where n is the number of features.

    Output:
    cost : float
        The accumulated mean squared error (MSE).
    """
    # Calculate the predicted values
    Y_pred = np.dot(X, W)

    # Calculate the squared errors
    errors = Y - Y_pred

    # Compute the Mean Squared Error (MSE)
    cost = np.mean(errors ** 2)

    return cost

# Define the gradient descent function
def gradient_descent(X, Y, W, alpha, iterations):
    """
    Perform gradient descent to optimize the parameters of a linear regression model.
    Parameters:
    X : numpy.ndarray
        Feature matrix (m x n).
    Y : numpy.ndarray
        Target vector (m x 1).
    W : numpy.ndarray
        Initial guess for parameters (n x 1).
    alpha : float
        Learning rate.
    iterations : int
        Number of iterations for gradient descent.

    Returns:
    W_update : numpy.ndarray
        Updated parameters (n x 1).
    cost_history : list
        History of cost values over iterations.
    """
    # Initialize cost history
    cost_history = []

    # Number of samples (m)
    m = len(Y)

    # Gradient descent loop
    for iteration in range(iterations):
        # Step 1: Hypothesis Values (hθ(X) = X * W)
        Y_pred = np.dot(X, W)

        # Step 2: Loss (Difference between predicted and actual values)
        loss = Y_pred - Y

        # Step 3: Gradient Calculation (dw = (2/m) * X^T * loss)
        dw = (2/m) * np.dot(X.T, loss)

        # Step 4: Update weights (W = W - alpha * dw)
        W_update = W - alpha * dw

        # Step 5: Calculate the new cost value and store it in cost_history
        cost = cost_function(X, Y, W_update)
        cost_history.append(cost)

        # Update weights for the next iteration
        W = W_update

    return W_update, cost_history

# Example Usage:

# Sample dataset (Feature matrix X and target vector Y)
X = np.array([[1, 3, 5],
              [2, 4, 6],
              [1, 3, 5],
              [2, 4, 6]])  # (4 samples, 3 features)

Y = np.array([3, 7, 3, 7])  # Target values (4 samples)

# Initialize weights (W) randomly or set to zeros
W_init = np.zeros(X.shape[1])  # (3 features)

# Set learning rate and number of iterations
alpha = 0.01
iterations = 1000

# Call gradient descent
W_optimal, cost_history = gradient_descent(X, Y, W_init, alpha, iterations)

# Print results
print("Optimized Weights:", W_optimal)
print("Final Cost:", cost_history[-1])
print("Cost History (first 10 iterations):", cost_history[:10])



Optimized Weights: [ 3.34235416  1.26765577 -0.80704262]
Final Cost: 0.009839845695018308
Cost History (first 10 iterations): [2.1872499999999997, 1.9468728849999999, 1.9346233499604994, 1.9243856735727318, 1.914218796443162, 1.9041057754430228, 1.894046183830464, 1.884039738111759, 1.874086157501067, 1.8641851627063604]


In [20]:
# Generate random test data
np.random.seed(0) # For reproducibility
X = np.random.rand(100, 3) # 100 samples, 3 features
Y = np.random.rand(100)
W = np.random.rand(3) # Initial guess for parameters
# Set hyperparameters
alpha = 0.01
iterations = 1000
# Test the gradient_descent function
final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)
# Print the final parameters and cost history
print("Final Parameters:", final_params)
print("Cost History:", cost_history)

Final Parameters: [0.19444407 0.46183379 0.18966481]
Cost History: [0.2126848827535125, 0.2096956540023033, 0.2068048415077832, 0.20400913903147738, 0.2013053516475558, 0.19869039199434624, 0.1961612766520831, 0.19371512264263963, 0.19134914404713463, 0.18906064873744627, 0.186847035217795, 0.1847057895726903, 0.18263448251765826, 0.1806307665492894, 0.17869237319126174, 0.17681711033310762, 0.17500285965859919, 0.17324757416073727, 0.17154927574042497, 0.16990605288600855, 0.16831605843096223, 0.16677750738708613, 0.16528867485067233, 0.16384789397918426, 0.16245355403607245, 0.16110409850143448, 0.15979802324629896, 0.15853387476839365, 0.1573102484873253, 0.156125787097171, 0.1549791789745484, 0.15386915664029455, 0.1527944952729508, 0.1517540112723064, 0.1507465608713166, 0.149771038794766, 0.14882637696310236, 0.1479115432399203, 0.14702554022162478, 0.14616740406785345, 0.1453362033712861, 0.14453103806551396, 0.14375103836968794, 0.14299536376870614, 0.14226320202774534, 0.14155

In [22]:
# Model Evaluation - RMSE
def rmse(Y, Y_pred):
    """
    This function calculates the Root Mean Squared Error (RMSE).

    Parameters:
    Y : numpy.ndarray
        Array of actual (target) dependent variables (m, ).
    Y_pred : numpy.ndarray
        Array of predicted dependent variables (m, ).

    Returns:
    rmse : float
        The root mean squared error.
    """
    # Step 1: Calculate the squared differences between actual and predicted values
    squared_differences = (Y - Y_pred) ** 2

    # Step 2: Calculate the mean of the squared differences
    mean_squared_error = np.mean(squared_differences)

    # Step 3: Take the square root of the mean squared error
    rmse_value = np.sqrt(mean_squared_error)

    return rmse_value

In [23]:

# Model Evaluation - R-squared
def r2(Y, Y_pred):
    """
    This function calculates the R Squared value, which measures the goodness of fit.

    Parameters:
    Y : numpy.ndarray
        Array of actual (target) dependent variables (m, ).
    Y_pred : numpy.ndarray
        Array of predicted dependent variables (m, ).

    Returns:
    r2 : float
        The R-squared value.
    """
    # Step 1: Calculate the mean of the actual values (Y)
    mean_y = np.mean(Y)

    # Step 2: Calculate the Total Sum of Squares (SST)
    ss_tot = np.sum((Y - mean_y) ** 2)

    # Step 3: Calculate the Sum of Squared Residuals (SSR)
    ss_res = np.sum((Y - Y_pred) ** 2)

    # Step 4: Calculate the R-squared value
    r2_value = 1 - (ss_res / ss_tot)

    return r2_value

In [25]:
# Gradient Descent Function (as you wrote earlier)
def gradient_descent(X, Y, W, alpha, iterations):
    cost_history = [0] * iterations
    m = len(Y)

    for iteration in range(iterations):
        # Step 1: Hypothesis Values
        Y_pred = np.dot(X, W)  # Predicted Y values
        # Step 2: Difference between Hypothesis and Actual Y
        loss = Y_pred - Y
        # Step 3: Gradient Calculation
        dw = (1/m) * np.dot(X.T, loss)  # Gradient for the weights
        # Step 4: Updating Values of W using Gradient
        W -= alpha * dw
        # Step 5: New Cost Value
        cost = cost_function(X, Y, W)
        cost_history[iteration] = cost

    return W, cost_history

# Cost Function
def cost_function(X, Y, W):
    m = len(Y)
    Y_pred = np.dot(X, W)
    cost = (1 / (2 * m)) * np.sum(np.square(Y_pred - Y))
    return cost

# Model Evaluation - RMSE
def rmse(Y, Y_pred):
    return np.sqrt(np.mean((Y - Y_pred) ** 2))

# Model Evaluation - R2
def r2(Y, Y_pred):
    ss_tot = np.sum((Y - np.mean(Y)) ** 2)
    ss_res = np.sum((Y - Y_pred) ** 2)
    r2 = 1 - (ss_res / ss_tot)
    return r2

# Main Function
def main():
    # Step 1: Load the dataset
    data = pd.read_csv("/content/drive/MyDrive/Datasets/student.csv")

    # Step 2: Split the data into features (X) and target (Y)
    X = data[['Math', 'Reading']].values  # Features: Math and Reading marks
    Y = data['Writing'].values  # Target: Writing marks

    # Step 3: Split the data into training and test sets (80% train, 20% test)
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

    # Step 4: Initialize weights (W) to zeros, learning rate and number of iterations
    W = np.zeros(X_train.shape[1])  # Initialize weights
    alpha = 0.00001  # Learning rate
    iterations = 1000  # Number of iterations for gradient descent

    # Step 5: Perform Gradient Descent
    W_optimal, cost_history = gradient_descent(X_train, Y_train, W, alpha, iterations)

    # Step 6: Make predictions on the test set
    Y_pred = np.dot(X_test, W_optimal)

    # Step 7: Evaluate the model using RMSE and R-Squared
    model_rmse = rmse(Y_test, Y_pred)
    model_r2 = r2(Y_test, Y_pred)

    # Step 8: Output the results
    print("Final Weights:", W_optimal)
    print("Cost History (First 10 iterations):", cost_history[:10])
    print("RMSE on Test Set:", model_rmse)
    print("R-Squared on Test Set:", model_r2)

# Execute the main function
if __name__ == "__main__":
    main()


Final Weights: [0.34811659 0.64614558]
Cost History (First 10 iterations): [2013.165570783755, 1640.286832599692, 1337.0619994901588, 1090.4794892850578, 889.9583270083234, 726.8940993009545, 594.2897260808594, 486.4552052951635, 398.7634463599484, 327.4517147324688]
RMSE on Test Set: 5.2798239764188635
R-Squared on Test Set: 0.8886354462786421


In [26]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# Function to calculate Cost (Mean Squared Error)
def cost_function(X, Y, W):
    m = len(Y)
    Y_pred = np.dot(X, W)
    cost = (1/(2*m)) * np.sum((Y_pred - Y) ** 2)
    return cost

# Gradient Descent function
def gradient_descent(X, Y, W, alpha, iterations):
    cost_history = []
    m = len(Y)
    for _ in range(iterations):
        Y_pred = np.dot(X, W)
        loss = Y_pred - Y
        dw = (1/m) * np.dot(X.T, loss)
        W = W - alpha * dw
        cost = cost_function(X, Y, W)
        cost_history.append(cost)
    return W, cost_history

# Root Mean Squared Error (RMSE)
def rmse(Y, Y_pred):
    return np.sqrt(np.mean((Y - Y_pred) ** 2))

# R-Squared function
def r2(Y, Y_pred):
    ss_tot = np.sum((Y - np.mean(Y)) ** 2)
    ss_res = np.sum((Y - Y_pred) ** 2)
    return 1 - (ss_res / ss_tot)

# Main Function to integrate all steps
def main():
    # Load the dataset
    data = pd.read_csv("/content/drive/MyDrive/Datasets/student.csv")  # Replace with your actual CSV file
    X = data[['Math', 'Reading']].values  # Features
    Y = data['Writing'].values  # Target

    # Split the dataset into training and test sets (80% train, 20% test)
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

    # Initialize weights, number of iterations, and learning rates
    W_initial = np.zeros(X_train.shape[1])
    iterations = 1000

    # Experiment with different learning rates
    learning_rates = [0.0001, 0.001, 0.01, 0.1, 0.5]

    for alpha in learning_rates:
        print(f"Experimenting with Learning Rate: {alpha}")

        # Train the model using Gradient Descent
        W_optimal, cost_history = gradient_descent(X_train, Y_train, W_initial, alpha, iterations)

        # Make predictions on the test set
        Y_pred = np.dot(X_test, W_optimal)

        # Evaluate the model
        model_rmse = rmse(Y_test, Y_pred)
        model_r2 = r2(Y_test, Y_pred)

        # Output the results
        print("Final Weights:", W_optimal)
        print("Final Cost (Last Iteration):", cost_history[-1])
        print("RMSE on Test Set:", model_rmse)
        print("R-Squared on Test Set:", model_r2)
        print("-" * 50)

# Execute the main function
if __name__ == "__main__":
    main()


Experimenting with Learning Rate: 0.0001
Final Weights: [0.0894932  0.89504864]
Final Cost (Last Iteration): 10.26076310841341
RMSE on Test Set: 4.792607360540954
R-Squared on Test Set: 0.908240340333986
--------------------------------------------------
Experimenting with Learning Rate: 0.001
Final Weights: [nan nan]
Final Cost (Last Iteration): nan
RMSE on Test Set: nan
R-Squared on Test Set: nan
--------------------------------------------------
Experimenting with Learning Rate: 0.01
Final Weights: [nan nan]
Final Cost (Last Iteration): nan
RMSE on Test Set: nan
R-Squared on Test Set: nan
--------------------------------------------------
Experimenting with Learning Rate: 0.1
Final Weights: [nan nan]
Final Cost (Last Iteration): nan
RMSE on Test Set: nan
R-Squared on Test Set: nan
--------------------------------------------------
Experimenting with Learning Rate: 0.5
Final Weights: [nan nan]
Final Cost (Last Iteration): nan
RMSE on Test Set: nan
R-Squared on Test Set: nan
---------

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
<ipython-input-26-8a2c0ac5d286>:9: RuntimeWarning: overflow encountered in square
  cost = (1/(2*m)) * np.sum((Y_pred - Y) ** 2)
<ipython-input-26-8a2c0ac5d286>:20: RuntimeWarning: invalid value encountered in subtract
  W = W - alpha * dw
